# 指定语言环境
language: node_js
# 指定需要sudo权限
sudo: required
# 指定node_js版本
node_js: stable
git:
  submodules: false
before_install:
  - npm install -g hexo-cli
install:
  - npm install
script:
  - git submodule init
  - git submodule update
  - hexo generate
after_success:
  - git config --global user.name "star936"
  - git config --global user.email "1542938982@qq.com"
  - sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
  - hexo deploy
branches:
  only:
  - hexo
