name: Hexo Deploy

on: # 触发条件
  push:
    branches:
      - hexo # 向hexo分支push时触发

jobs:
  build:
    name: Build and publish 
    runs-on: ubuntu-latest # 运行环境

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: hexo

      - name: Use Node.js 8.x
        uses: actions/setup-node@v1
        with:
          node-version: 8.x

      - name: Setup hexo
        env:
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACCESS_TOKEN_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "star936"
          git config --global user.email "1542938982@qq.com"
          npm install hexo-cli -g
          npm install

      - name: Clean & Generate & Deploy
        run: |
          hexo clean
          hexo generate 
          hexo deploy